import { RecipeT } from '@/common/types/recipes';

export class RecipesUiFct {
  public static readonly data: RecipeT[] = [
    {
      id: '1',
      name: 'Mediterranean Chickpea Salad',
      description: 'A refreshing, protein-packed salad tossed in a lemon-olive oil dressing.',
      servings: 2,
      prep: '10',
      cook: '0',
      img: '/images/chickpea_salad.webp',
      ingredients: [
        { id: '1-1', ingredient: '1 can (400 g) chickpeas, drained & rinsed' },
        { id: '1-2', ingredient: '1 small cucumber, diced' },
        { id: '1-3', ingredient: '1 cup cherry tomatoes, halved' },
        { id: '1-4', ingredient: '1/2 red bell pepper, diced' },
        { id: '1-5', ingredient: '1/4 red onion, finely chopped' },
        { id: '1-6', ingredient: '2 Tbsp fresh parsley, chopped' },
        { id: '1-7', ingredient: '2 Tbsp extra-virgin olive oil' },
        { id: '1-8', ingredient: '1 Tbsp fresh lemon juice' },
        { id: '1-9', ingredient: 'Sea salt & black pepper to taste' },
      ],
      instructions: [
        {
          id: '1-1',
          instruction:
            'In a large bowl combine chickpeas, cucumber, tomatoes, bell pepper, red onion and parsley.',
        },
        { id: '1-2', instruction: 'Drizzle with olive oil and lemon juice.' },
        { id: '1-3', instruction: 'Season with salt and pepper; toss to coat.' },
        { id: '1-4', instruction: 'Serve immediately or chill up to 2 days.' },
      ],
    },
    {
      id: '2',
      name: 'Avocado & Tomato Wholegrain Toast',
      description:
        'Creamy avocado spread over toasted wholegrain bread, topped with juicy tomatoes.',
      servings: 1,
      prep: '5',
      cook: '5',
      img: '/images/avocado_tomato.webp',
      ingredients: [
        { id: '2-1', ingredient: '2 slices wholegrain bread' },
        { id: '2-2', ingredient: '1 ripe avocado' },
        { id: '2-3', ingredient: '6 cherry tomatoes, quartered' },
        { id: '2-4', ingredient: '1 tsp extra-virgin olive oil' },
        { id: '2-5', ingredient: '1 tsp fresh lemon juice' },
        { id: '2-6', ingredient: 'Sea salt, black pepper, pinch chili flakes' },
      ],
      instructions: [
        { id: '2-1', instruction: 'Toast the bread to desired crispness.' },
        { id: '2-2', instruction: 'Mash avocado with lemon juice, salt and pepper.' },
        { id: '2-3', instruction: 'Spread avocado on toast and top with tomatoes.' },
        { id: '2-4', instruction: 'Drizzle olive oil and sprinkle chili flakes.' },
      ],
    },
    {
      id: '3',
      name: 'One-Pan Lemon Garlic Salmon with Asparagus',
      description: 'A 15-minute weeknight dinner of flaky salmon and tender asparagus.',
      servings: 2,
      prep: '5',
      cook: '12',
      img: '/images/salmon_asparagus.webp',
      ingredients: [
        { id: '3-1', ingredient: '2 salmon fillets (125 g each)' },
        { id: '3-2', ingredient: '200 g asparagus spears, trimmed' },
        { id: '3-3', ingredient: '1 Tbsp extra-virgin olive oil' },
        { id: '3-4', ingredient: '2 garlic cloves, minced' },
        { id: '3-5', ingredient: '1/2 lemon, sliced' },
        { id: '3-6', ingredient: 'Sea salt & black pepper' },
      ],
      instructions: [
        { id: '3-1', instruction: 'Heat a large skillet over medium-high with olive oil.' },
        {
          id: '3-2',
          instruction: 'Season salmon and asparagus with salt, pepper, and minced garlic.',
        },
        { id: '3-3', instruction: 'Place salmon skin-side down; arrange asparagus around.' },
        {
          id: '3-4',
          instruction:
            'Cook 4 min, flip salmon, add lemon slices, cook 4-5 min more until salmon is opaque.',
        },
        { id: '3-5', instruction: 'Serve hot with pan juices.' },
      ],
    },
    {
      id: '4',
      name: 'Quinoa Veggie Power Bowl',
      description: 'A balanced bowl of fluffy quinoa, roasted veggies and healthy fats.',
      servings: 2,
      prep: '10',
      cook: '15',
      img: '/images/quinoa.webp',
      ingredients: [
        { id: '4-1', ingredient: '1 cup cooked quinoa (from 1/3 cup dry)' },
        { id: '4-2', ingredient: '1 cup roasted sweet potato cubes' },
        { id: '4-3', ingredient: '1 cup baby spinach' },
        { id: '4-4', ingredient: '1/2 cup chickpeas, drained & rinsed' },
        { id: '4-5', ingredient: '1/2 avocado, sliced' },
        { id: '4-6', ingredient: '1 Tbsp pumpkin seeds' },
        { id: '4-7', ingredient: '1 Tbsp extra-virgin olive oil' },
        { id: '4-8', ingredient: '1 Tbsp fresh lemon juice' },
        { id: '4-9', ingredient: 'Sea salt & black pepper' },
      ],
      instructions: [
        { id: '4-1', instruction: 'Cook quinoa according to package, fluff and cool slightly.' },
        { id: '4-2', instruction: 'In bowls layer spinach, quinoa, sweet potato and chickpeas.' },
        { id: '4-3', instruction: 'Top with avocado slices and pumpkin seeds.' },
        {
          id: '4-4',
          instruction: 'Whisk olive oil, lemon juice, salt & pepper; drizzle over bowls.',
        },
      ],
    },
    {
      id: '5',
      name: 'Sweet Potato Black Bean Tacos',
      description: 'Smoky roasted sweet potatoes and black beans tucked into warm tortillas.',
      servings: 3,
      prep: '10',
      cook: '15',
      img: '/images/tacos.webp',
      ingredients: [
        { id: '5-1', ingredient: '6 small corn tortillas' },
        { id: '5-2', ingredient: '1 medium sweet potato, diced small' },
        { id: '5-3', ingredient: '1 cup canned black beans, rinsed' },
        { id: '5-4', ingredient: '1 Tbsp olive oil' },
        { id: '5-5', ingredient: '1/2 tsp ground cumin' },
        { id: '5-6', ingredient: '1/2 tsp smoked paprika' },
        { id: '5-7', ingredient: 'Juice of 1/2 lime' },
        { id: '5-8', ingredient: '1/2 cup shredded red cabbage' },
        { id: '5-9', ingredient: 'Fresh cilantro & salsa to serve' },
      ],
      instructions: [
        {
          id: '5-1',
          instruction:
            'Toss sweet potato cubes with oil, cumin, paprika, salt; roast in air-fryer or oven at 200 °C for 12 min.',
        },
        { id: '5-2', instruction: 'Warm tortillas in a dry skillet.' },
        {
          id: '5-3',
          instruction: 'Fill tortillas with roasted sweet potatoes, black beans and cabbage.',
        },
        { id: '5-4', instruction: 'Squeeze lime juice, add salsa and cilantro.' },
      ],
    },
    {
      id: '6',
      name: 'Greek Yogurt Berry Parfait',
      description:
        'Layers of creamy yogurt, fresh berries and crunchy oats for a high-protein snack.',
      servings: 1,
      prep: '5',
      cook: '0',
      img: '/images/yogurt.webp',
      ingredients: [
        { id: '6-1', ingredient: '1 cup plain Greek yogurt' },
        { id: '6-2', ingredient: '1/2 cup mixed fresh berries' },
        { id: '6-3', ingredient: '2 Tbsp rolled oats' },
        { id: '6-4', ingredient: '1 tsp honey' },
        { id: '6-5', ingredient: '1 tsp chia seeds' },
      ],
      instructions: [
        { id: '6-1', instruction: 'In a glass, layer half the yogurt, berries and oats.' },
        { id: '6-2', instruction: 'Repeat layers and drizzle with honey.' },
        { id: '6-3', instruction: 'Sprinkle chia seeds and serve.' },
      ],
    },
    {
      id: '7',
      name: 'Lentil & Spinach Soup',
      description: 'A hearty 30-minute soup rich in plant protein and iron.',
      servings: 4,
      prep: '10',
      cook: '20',
      img: '/images/lentil.webp',
      ingredients: [
        { id: '7-1', ingredient: '1 Tbsp olive oil' },
        { id: '7-2', ingredient: '1 onion, diced' },
        { id: '7-3', ingredient: '1 carrot, diced' },
        { id: '7-4', ingredient: '1 celery stalk, diced' },
        { id: '7-5', ingredient: '2 garlic cloves, minced' },
        { id: '7-6', ingredient: '1 cup dry red lentils, rinsed' },
        { id: '7-7', ingredient: '400 g canned diced tomatoes' },
        { id: '7-8', ingredient: '4 cups vegetable broth' },
        { id: '7-9', ingredient: '2 cups baby spinach' },
        { id: '7-10', ingredient: '1/2 tsp ground cumin' },
        { id: '7-11', ingredient: 'Sea salt & black pepper' },
      ],
      instructions: [
        { id: '7-1', instruction: 'Heat oil in a pot; sauté onion, carrot, celery 4 min.' },
        { id: '7-2', instruction: 'Add garlic & cumin; cook 1 min.' },
        { id: '7-3', instruction: 'Stir in lentils, tomatoes and broth; bring to boil.' },
        { id: '7-4', instruction: 'Simmer 15 min until lentils tender.' },
        { id: '7-5', instruction: 'Stir in spinach until wilted, season and serve.' },
      ],
    },
    {
      id: '8',
      name: 'Banana Oat Pancakes',
      description: 'Flour-free pancakes sweetened naturally with ripe bananas.',
      servings: 2,
      prep: '5',
      cook: '10',
      img: '/images/pancakes.webp',
      ingredients: [
        { id: '8-1', ingredient: '2 ripe bananas' },
        { id: '8-2', ingredient: '1 cup rolled oats' },
        { id: '8-3', ingredient: '2 eggs' },
        { id: '8-4', ingredient: '1 tsp baking powder' },
        { id: '8-5', ingredient: '1/2 tsp cinnamon' },
        { id: '8-6', ingredient: 'Olive oil for cooking' },
        { id: '8-7', ingredient: 'Fresh fruit to serve' },
      ],
      instructions: [
        {
          id: '8-1',
          instruction: 'Blend bananas, oats, eggs, baking powder and cinnamon until smooth.',
        },
        {
          id: '8-2',
          instruction: 'Heat lightly oiled skillet on medium; pour 1/4-cup batter circles.',
        },
        { id: '8-3', instruction: 'Cook 2-3 min each side until golden.' },
        { id: '8-4', instruction: 'Serve with fresh fruit.' },
      ],
    },
  ];
}
